/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import controlResiduosPeligrosos.FabricaN;
import controlResiduosPeligrosos.INegocio;
import entidades.*;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author giova
 */
public class AdministracionForm extends javax.swing.JFrame {

    private INegocio negocio = FabricaN.fabricaN();
    private List<Transporte> listaTrasportistas;

    public AdministracionForm() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistro = new javax.swing.JPanel();
        btnRegProductor = new javax.swing.JButton();
        btnRegTransporte = new javax.swing.JButton();
        btnRegQuimico = new javax.swing.JButton();
        lblRegistrar = new javax.swing.JLabel();
        btnRegAdministrador = new javax.swing.JButton();
        btnSaliRegistro = new javax.swing.JButton();
        btnRegVehiculo = new javax.swing.JButton();
        pnlRegQuimico = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnAgregarQuimico = new javax.swing.JButton();
        btnSalirQuimico = new javax.swing.JButton();
        lblNombreQuimico = new javax.swing.JLabel();
        txtNombreQuimico = new javax.swing.JTextField();
        pnlRegproductor = new javax.swing.JPanel();
        lblRegistrarProductor = new javax.swing.JLabel();
        lblNombreRegProductor = new javax.swing.JLabel();
        txtNombreRegProductor = new javax.swing.JTextField();
        lblContraseniaRegProductor = new javax.swing.JLabel();
        txtContraseniaRegProductor = new javax.swing.JTextField();
        btnAgregarProductor = new javax.swing.JButton();
        btnSalirProductor = new javax.swing.JButton();
        pnlRegTransporte = new javax.swing.JPanel();
        lblRegistrarTransportista = new javax.swing.JLabel();
        lblNombreRegTransportista = new javax.swing.JLabel();
        lblContraseniaRegTransportista = new javax.swing.JLabel();
        txtNombreRegTransportista = new javax.swing.JTextField();
        txtContraseniaRegTransportista = new javax.swing.JTextField();
        btnAgregarRegTransportista = new javax.swing.JButton();
        btnSalirRegTransportista = new javax.swing.JButton();
        pnlRegAdministrador = new javax.swing.JPanel();
        lblRegistrarAdministrador = new javax.swing.JLabel();
        lblNombreRegAdministrador = new javax.swing.JLabel();
        lblContraseniaRegAdministrador = new javax.swing.JLabel();
        txtNombreRegAdministrador = new javax.swing.JTextField();
        txtContraseniaRegAdministrador = new javax.swing.JTextField();
        btnAgregarRegAdministrador = new javax.swing.JButton();
        btnSalirRegvAdministrador = new javax.swing.JButton();
        pnlRegVehiculo = new javax.swing.JPanel();
        lblRegistroVehiculos = new javax.swing.JLabel();
        lblTransportistaRegVh = new javax.swing.JLabel();
        cmbTransportistaRegVh = new javax.swing.JComboBox<>();
        lblTipoVehiculoRegVh = new javax.swing.JLabel();
        txtTipoVehiculoRegVh = new javax.swing.JTextField();
        lblPlacasRegVh = new javax.swing.JLabel();
        txtPlacasRegVh = new javax.swing.JTextField();
        btnGuardarRegVh = new javax.swing.JButton();
        btnSalirRegVh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administración");
        getContentPane().setLayout(new java.awt.CardLayout());

        btnRegProductor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegProductor.setText("Productor");
        btnRegProductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegProductorActionPerformed(evt);
            }
        });

        btnRegTransporte.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegTransporte.setText("Transporte");
        btnRegTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegTransporteActionPerformed(evt);
            }
        });

        btnRegQuimico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegQuimico.setText("Químico");
        btnRegQuimico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegQuimicoActionPerformed(evt);
            }
        });

        lblRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblRegistrar.setText("Registrar:");

        btnRegAdministrador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegAdministrador.setText("Administrador");
        btnRegAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegAdministradorActionPerformed(evt);
            }
        });

        btnSaliRegistro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSaliRegistro.setText("Salir");
        btnSaliRegistro.setPreferredSize(new java.awt.Dimension(81, 26));
        btnSaliRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaliRegistroActionPerformed(evt);
            }
        });

        btnRegVehiculo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegVehiculo.setText("Vehículo");
        btnRegVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistroLayout = new javax.swing.GroupLayout(pnlRegistro);
        pnlRegistro.setLayout(pnlRegistroLayout);
        pnlRegistroLayout.setHorizontalGroup(
            pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroLayout.createSequentialGroup()
                        .addComponent(btnSaliRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroLayout.createSequentialGroup()
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegAdministrador)
                            .addComponent(btnRegProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegQuimico, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))))
        );
        pnlRegistroLayout.setVerticalGroup(
            pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistrar)
                    .addComponent(btnRegQuimico))
                .addGap(18, 18, 18)
                .addComponent(btnRegProductor)
                .addGap(18, 18, 18)
                .addComponent(btnRegAdministrador)
                .addGap(18, 18, 18)
                .addComponent(btnRegTransporte)
                .addGap(18, 18, 18)
                .addComponent(btnRegVehiculo)
                .addGap(18, 18, 18)
                .addComponent(btnSaliRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(pnlRegistro, "registro");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Registro de Quimico");

        btnAgregarQuimico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregarQuimico.setText("Agregar");
        btnAgregarQuimico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarQuimicoActionPerformed(evt);
            }
        });

        btnSalirQuimico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalirQuimico.setText("Salir");
        btnSalirQuimico.setPreferredSize(new java.awt.Dimension(81, 26));
        btnSalirQuimico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirQuimicoActionPerformed(evt);
            }
        });

        lblNombreQuimico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombreQuimico.setText("Nombre:");

        txtNombreQuimico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlRegQuimicoLayout = new javax.swing.GroupLayout(pnlRegQuimico);
        pnlRegQuimico.setLayout(pnlRegQuimicoLayout);
        pnlRegQuimicoLayout.setHorizontalGroup(
            pnlRegQuimicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegQuimicoLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(pnlRegQuimicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(pnlRegQuimicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRegQuimicoLayout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(btnAgregarQuimico)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalirQuimico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRegQuimicoLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(lblNombreQuimico)
                            .addGap(18, 18, 18)
                            .addComponent(txtNombreQuimico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45))
        );
        pnlRegQuimicoLayout.setVerticalGroup(
            pnlRegQuimicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegQuimicoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitulo)
                .addGap(33, 33, 33)
                .addGroup(pnlRegQuimicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreQuimico)
                    .addComponent(txtNombreQuimico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(pnlRegQuimicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarQuimico)
                    .addComponent(btnSalirQuimico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );

        getContentPane().add(pnlRegQuimico, "regQuimico");

        lblRegistrarProductor.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblRegistrarProductor.setText("Registrar Productor");

        lblNombreRegProductor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombreRegProductor.setText("Nombre");

        txtNombreRegProductor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombreRegProductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreRegProductorActionPerformed(evt);
            }
        });

        lblContraseniaRegProductor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblContraseniaRegProductor.setText("Contraseña");

        txtContraseniaRegProductor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtContraseniaRegProductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseniaRegProductorActionPerformed(evt);
            }
        });

        btnAgregarProductor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregarProductor.setText("Agregar");
        btnAgregarProductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductorActionPerformed(evt);
            }
        });

        btnSalirProductor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalirProductor.setText("Salir");
        btnSalirProductor.setPreferredSize(new java.awt.Dimension(81, 26));
        btnSalirProductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirProductorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegproductorLayout = new javax.swing.GroupLayout(pnlRegproductor);
        pnlRegproductor.setLayout(pnlRegproductorLayout);
        pnlRegproductorLayout.setHorizontalGroup(
            pnlRegproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegproductorLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(pnlRegproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegistrarProductor)
                    .addGroup(pnlRegproductorLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(pnlRegproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlRegproductorLayout.createSequentialGroup()
                                .addComponent(btnAgregarProductor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalirProductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRegproductorLayout.createSequentialGroup()
                                .addGroup(pnlRegproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNombreRegProductor)
                                    .addComponent(lblContraseniaRegProductor))
                                .addGap(18, 18, 18)
                                .addGroup(pnlRegproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtContraseniaRegProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreRegProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        pnlRegproductorLayout.setVerticalGroup(
            pnlRegproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegproductorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblRegistrarProductor)
                .addGap(30, 30, 30)
                .addGroup(pnlRegproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRegProductor)
                    .addComponent(txtNombreRegProductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(pnlRegproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseniaRegProductor)
                    .addComponent(txtContraseniaRegProductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(pnlRegproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalirProductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarProductor))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(pnlRegproductor, "regProductor");

        lblRegistrarTransportista.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblRegistrarTransportista.setText("Registro de Trasportista");

        lblNombreRegTransportista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreRegTransportista.setText("Nombre:");

        lblContraseniaRegTransportista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblContraseniaRegTransportista.setText("Contraseña");

        txtNombreRegTransportista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreRegTransportista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreRegTransportistaActionPerformed(evt);
            }
        });

        txtContraseniaRegTransportista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnAgregarRegTransportista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregarRegTransportista.setText("Agregar");
        btnAgregarRegTransportista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRegTransportistaActionPerformed(evt);
            }
        });

        btnSalirRegTransportista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalirRegTransportista.setText("Salir");
        btnSalirRegTransportista.setPreferredSize(new java.awt.Dimension(81, 26));
        btnSalirRegTransportista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirRegTransportistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegTransporteLayout = new javax.swing.GroupLayout(pnlRegTransporte);
        pnlRegTransporte.setLayout(pnlRegTransporteLayout);
        pnlRegTransporteLayout.setHorizontalGroup(
            pnlRegTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegTransporteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlRegTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegistrarTransportista)
                    .addGroup(pnlRegTransporteLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(pnlRegTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblContraseniaRegTransportista)
                            .addComponent(lblNombreRegTransportista)
                            .addComponent(btnAgregarRegTransportista))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlRegTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtContraseniaRegTransportista, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombreRegTransportista, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSalirRegTransportista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlRegTransporteLayout.setVerticalGroup(
            pnlRegTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegTransporteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblRegistrarTransportista)
                .addGap(43, 43, 43)
                .addGroup(pnlRegTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRegTransportista)
                    .addComponent(txtNombreRegTransportista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlRegTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContraseniaRegTransportista)
                    .addComponent(txtContraseniaRegTransportista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(pnlRegTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarRegTransportista)
                    .addComponent(btnSalirRegTransportista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        getContentPane().add(pnlRegTransporte, "regTransporte");

        lblRegistrarAdministrador.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblRegistrarAdministrador.setText("Registro de Administrador");

        lblNombreRegAdministrador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreRegAdministrador.setText("Nombre:");

        lblContraseniaRegAdministrador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblContraseniaRegAdministrador.setText("Contraseña");

        txtNombreRegAdministrador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreRegAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreRegAdministradorActionPerformed(evt);
            }
        });

        txtContraseniaRegAdministrador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnAgregarRegAdministrador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregarRegAdministrador.setText("Agregar");
        btnAgregarRegAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRegAdministradorActionPerformed(evt);
            }
        });

        btnSalirRegvAdministrador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalirRegvAdministrador.setText("Salir");
        btnSalirRegvAdministrador.setPreferredSize(new java.awt.Dimension(81, 26));
        btnSalirRegvAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirRegvAdministradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegAdministradorLayout = new javax.swing.GroupLayout(pnlRegAdministrador);
        pnlRegAdministrador.setLayout(pnlRegAdministradorLayout);
        pnlRegAdministradorLayout.setHorizontalGroup(
            pnlRegAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegAdministradorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlRegAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegistrarAdministrador)
                    .addGroup(pnlRegAdministradorLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(pnlRegAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblContraseniaRegAdministrador)
                            .addComponent(lblNombreRegAdministrador)
                            .addComponent(btnAgregarRegAdministrador))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlRegAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtContraseniaRegAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombreRegAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSalirRegvAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRegAdministradorLayout.setVerticalGroup(
            pnlRegAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegAdministradorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblRegistrarAdministrador)
                .addGap(43, 43, 43)
                .addGroup(pnlRegAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRegAdministrador)
                    .addComponent(txtNombreRegAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlRegAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContraseniaRegAdministrador)
                    .addComponent(txtContraseniaRegAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(pnlRegAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarRegAdministrador)
                    .addComponent(btnSalirRegvAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        getContentPane().add(pnlRegAdministrador, "regAdministrador");

        pnlRegVehiculo.setPreferredSize(new java.awt.Dimension(430, 332));

        lblRegistroVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblRegistroVehiculos.setText("Registro de Vehículos");

        lblTransportistaRegVh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTransportistaRegVh.setText("Transportista:");

        lblTipoVehiculoRegVh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipoVehiculoRegVh.setText("Tipo de Vehículo:");

        txtTipoVehiculoRegVh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoVehiculoRegVhActionPerformed(evt);
            }
        });

        lblPlacasRegVh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPlacasRegVh.setText("Placas:");

        btnGuardarRegVh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarRegVh.setText("Guardar");
        btnGuardarRegVh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRegVhActionPerformed(evt);
            }
        });

        btnSalirRegVh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalirRegVh.setText("Salir");
        btnSalirRegVh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirRegVhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegVehiculoLayout = new javax.swing.GroupLayout(pnlRegVehiculo);
        pnlRegVehiculo.setLayout(pnlRegVehiculoLayout);
        pnlRegVehiculoLayout.setHorizontalGroup(
            pnlRegVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegVehiculoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlRegVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegVehiculoLayout.createSequentialGroup()
                        .addGroup(pnlRegVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTipoVehiculoRegVh)
                            .addComponent(lblTransportistaRegVh)
                            .addComponent(lblPlacasRegVh))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbTransportistaRegVh, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTipoVehiculoRegVh, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPlacasRegVh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlRegVehiculoLayout.createSequentialGroup()
                                .addComponent(btnGuardarRegVh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalirRegVh))))
                    .addComponent(lblRegistroVehiculos))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pnlRegVehiculoLayout.setVerticalGroup(
            pnlRegVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegVehiculoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblRegistroVehiculos)
                .addGap(53, 53, 53)
                .addGroup(pnlRegVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTransportistaRegVh)
                    .addComponent(cmbTransportistaRegVh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlRegVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoVehiculoRegVh)
                    .addComponent(txtTipoVehiculoRegVh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPlacasRegVh)
                    .addComponent(txtPlacasRegVh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(pnlRegVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarRegVh)
                    .addComponent(btnSalirRegVh))
                .addGap(44, 44, 44))
        );

        getContentPane().add(pnlRegVehiculo, "regVehiculo");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegProductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegProductorActionPerformed
        CardLayout cl = (CardLayout) (this.getContentPane().getLayout());
        cl.show(this.getContentPane(), "regProductor");
        this.setTitle("Registro de Productor");
    }//GEN-LAST:event_btnRegProductorActionPerformed

    private void btnRegTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegTransporteActionPerformed
        CardLayout cl = (CardLayout) (this.getContentPane().getLayout());
        cl.show(this.getContentPane(), "regTransporte");
        this.setTitle("Registro de Transporte");
    }//GEN-LAST:event_btnRegTransporteActionPerformed

    private void btnAgregarQuimicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarQuimicoActionPerformed
        // TODO add your handling code here:
        agregarQuimico();

    }//GEN-LAST:event_btnAgregarQuimicoActionPerformed

    private void btnRegQuimicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegQuimicoActionPerformed
        //quimicosDAO = new QuimicosDAO(new ConexionBD());
        CardLayout cl = (CardLayout) (this.getContentPane().getLayout());
        cl.show(this.getContentPane(), "regQuimico");
        this.setTitle("Registro de Quimico");
    }//GEN-LAST:event_btnRegQuimicoActionPerformed

    private void btnSalirQuimicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirQuimicoActionPerformed
        // TODO add your handling code here:

        regresar();
    }//GEN-LAST:event_btnSalirQuimicoActionPerformed

    private void btnSaliRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaliRegistroActionPerformed

        dispose();
    }//GEN-LAST:event_btnSaliRegistroActionPerformed

    private void txtNombreRegProductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreRegProductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreRegProductorActionPerformed

    private void txtContraseniaRegProductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseniaRegProductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseniaRegProductorActionPerformed

    private void btnAgregarProductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductorActionPerformed
        agregarProductor();
    }//GEN-LAST:event_btnAgregarProductorActionPerformed

    private void btnSalirProductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirProductorActionPerformed
        // TODO add your handling code here:
        regresar();
    }//GEN-LAST:event_btnSalirProductorActionPerformed

    private void txtNombreRegTransportistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreRegTransportistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreRegTransportistaActionPerformed

    private void txtNombreRegAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreRegAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreRegAdministradorActionPerformed

    private void btnRegAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegAdministradorActionPerformed
        CardLayout cl = (CardLayout) (this.getContentPane().getLayout());
        cl.show(this.getContentPane(), "regAdministrador");
        this.setTitle("Registro de Administrador");
    }//GEN-LAST:event_btnRegAdministradorActionPerformed

    private void btnSalirRegTransportistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirRegTransportistaActionPerformed
        regresar();
    }//GEN-LAST:event_btnSalirRegTransportistaActionPerformed

    private void btnSalirRegvAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirRegvAdministradorActionPerformed
        regresar();
    }//GEN-LAST:event_btnSalirRegvAdministradorActionPerformed

    private void btnRegVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegVehiculoActionPerformed
        llenarCajaTrasnportistasRegVeh();

        CardLayout cl = (CardLayout) (this.getContentPane().getLayout());
        cl.show(this.getContentPane(), "regVehiculo");
        this.setTitle("Registro de Vehículo");

    }//GEN-LAST:event_btnRegVehiculoActionPerformed

    private void txtTipoVehiculoRegVhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoVehiculoRegVhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoVehiculoRegVhActionPerformed

    private void btnSalirRegVhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirRegVhActionPerformed
        regresar();
    }//GEN-LAST:event_btnSalirRegVhActionPerformed

    private void btnAgregarRegAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRegAdministradorActionPerformed

        agregarAdministrador();
    }//GEN-LAST:event_btnAgregarRegAdministradorActionPerformed

    private void btnGuardarRegVhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRegVhActionPerformed

    }//GEN-LAST:event_btnGuardarRegVhActionPerformed

    private void btnAgregarRegTransportistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRegTransportistaActionPerformed
        agregarTrasnporte();
    }//GEN-LAST:event_btnAgregarRegTransportistaActionPerformed

    private void regresar() {
        CardLayout cl = (CardLayout) (this.getContentPane().getLayout());
        cl.show(this.getContentPane(), "registro");
        this.setTitle("Administración");
    }

    private void limpiarQumico() {
        txtNombreQuimico.setText("");
    }

    private void limpiarProductor() {
        txtNombreRegProductor.setText("");
        txtContraseniaRegProductor.setText("");
    }

    private void agregarQuimico() {
        String nombreQuimico = this.txtNombreQuimico.getText().toUpperCase();
        if (!campoVacio(nombreQuimico)) {

            if (negocio.consultarExisteNombreQuimico(nombreQuimico)) {
                JOptionPane.showMessageDialog(this, "El quimico ya existe", "error", JOptionPane.ERROR_MESSAGE);
            } else {
                Quimico quimico = new Quimico(nombreQuimico);
                boolean seAgrego = negocio.agregarQuimico(quimico);
                if (seAgrego) {
                    JOptionPane.showMessageDialog(this, "Se agrego el químico", "información", JOptionPane.INFORMATION_MESSAGE);
                    this.limpiarQumico();
                } else {
                    JOptionPane.showMessageDialog(this, "No fue posible agregar el químico", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "No puede haber campos vacíos", "información", JOptionPane.INFORMATION_MESSAGE);
        }

    }//end agregarQuimico

    private void agregarProductor() {
        String nombreProductor = this.txtNombreRegProductor.getText().toUpperCase();
        String contrasenia = this.txtContraseniaRegProductor.getText();
        if (!campoVacio(nombreProductor) && !campoVacio(contrasenia)) {

            if (negocio.consultarExisteNombreProductor(nombreProductor)) {
                JOptionPane.showMessageDialog(this, "El Productor ya existe", "error", JOptionPane.ERROR_MESSAGE);
            } else {
                Productor productor = new Productor(nombreProductor, contrasenia);
                boolean seAgrego = negocio.agregarProductor(productor);
                if (seAgrego) {
                    JOptionPane.showMessageDialog(this, "Se registro el productor", "información", JOptionPane.INFORMATION_MESSAGE);
                    this.limpiarProductor();
                } else {
                    JOptionPane.showMessageDialog(this, "No fue posible registrar al productor", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "No puede haber campos vacíos", "información", JOptionPane.INFORMATION_MESSAGE);
        }

    }//end agregarProductor

    private void agregarAdministrador() {
        String nombreAdministrador = this.txtNombreRegAdministrador.getText().toUpperCase();
        String contrasenia = this.txtContraseniaRegAdministrador.getText();
        if (!campoVacio(nombreAdministrador) && !campoVacio(contrasenia)) {

            if (negocio.consultarExisteNombreAdministrador(nombreAdministrador)) {
                JOptionPane.showMessageDialog(this, "El Administrador ya existe", "error", JOptionPane.ERROR_MESSAGE);
            } else {
                Administrador administrador = new Administrador(nombreAdministrador, contrasenia);
                boolean seAgrego = negocio.agregarAdministrador(administrador);
                if (seAgrego) {
                    JOptionPane.showMessageDialog(this, "Se registro el administrador", "información", JOptionPane.INFORMATION_MESSAGE);
                    this.limpiarProductor();
                } else {
                    JOptionPane.showMessageDialog(this, "No fue posible registrar al administrador", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "No puede haber campos vacíos", "información", JOptionPane.INFORMATION_MESSAGE);
        }

    }//end agregarAdministrador

    private void agregarTrasnporte() {
        String nombreTrasnporte = this.txtNombreRegTransportista.getText().toUpperCase();
        String contrasenia = this.txtContraseniaRegTransportista.getText();
        //String transportista = this.cmbTransportistaRegVh.
        if (!campoVacio(nombreTrasnporte) && !campoVacio(contrasenia)) {

            if (negocio.consultarExisteNombretrasnporte(nombreTrasnporte)) {
                JOptionPane.showMessageDialog(this, "El Trasnportista ya existe", "error", JOptionPane.ERROR_MESSAGE);
            } else {
                Transporte transporte = new Transporte(nombreTrasnporte, contrasenia);
                boolean seAgrego = negocio.agregarTrasnporte(transporte);
                if (seAgrego) {
                    JOptionPane.showMessageDialog(this, "Se registro el Trasnportista", "información", JOptionPane.INFORMATION_MESSAGE);
                    this.limpiarProductor();
                } else {
                    JOptionPane.showMessageDialog(this, "No fue posible registrar al transportista", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "No puede haber campos vacíos", "información", JOptionPane.INFORMATION_MESSAGE);
        }

    }//end agregarTransporte

    private void agregarVehiculo() {
        String tipoVehiculo = this.txtTipoVehiculoRegVh.getText().toUpperCase();
        String placas = this.txtPlacasRegVh.getText();

        if (!campoVacio(tipoVehiculo) && !campoVacio(placas)) {

            if (negocio.consultarExistePlacaVehiculo(placas)) {
                JOptionPane.showMessageDialog(this, "Las placas ya existen", "error", JOptionPane.ERROR_MESSAGE);
            } else {
                Vehiculo vehiculo = new Vehiculo(tipoVehiculo, placas);
                boolean seAgrego = negocio.agregarVehiculo(vehiculo);
                if (seAgrego) {
                    JOptionPane.showMessageDialog(this, "Se registro el Vehículo", "información", JOptionPane.INFORMATION_MESSAGE);
                    this.limpiarProductor();
                } else {
                    JOptionPane.showMessageDialog(this, "No fue posible registrar el vehículo", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "No puede haber campos vacíos", "información", JOptionPane.INFORMATION_MESSAGE);
        }

    }//end agregarVehículo

    private boolean campoVacio(String campo) {
        int tamañoCampo = campo.length();
        if (tamañoCampo <= 0) {
            return true;
        }
        return false;
    }

    private void llenarCajaTrasnportistasRegVeh() {
        
        listaTrasportistas = negocio.consultarTodosTrasnportes();
        
        for(int i =0; i < listaTrasportistas.size(); i++){
            cmbTransportistaRegVh.addItem(listaTrasportistas.get(i).getNombre());
        }
/*
        ArrayList<Transporte> listaTransporte = (ArrayList<Transporte>) negocio.consultarTodosTrasnportes();
        cmbTransportistaRegVh.removeAll();

        for (int i = 0; i < listaTransporte.size(); i++) {
            cmbTransportistaRegVh.addItem(listaTransporte.get(i).getNombre());
        }
*/
    }

    /*
    public void llenarCajaIdLugares() {
        ArrayList<String> listaLugares = new ArrayList<>();
        listaLugares = this.eventosDAO.consultarIdLugares();

        for (int i = 0; i < listaLugares.size(); i++) {
            cmbIdLugar.addItem(listaLugares.get(i));
        }
    }
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProductor;
    private javax.swing.JButton btnAgregarQuimico;
    private javax.swing.JButton btnAgregarRegAdministrador;
    private javax.swing.JButton btnAgregarRegTransportista;
    private javax.swing.JButton btnGuardarRegVh;
    private javax.swing.JButton btnRegAdministrador;
    private javax.swing.JButton btnRegProductor;
    private javax.swing.JButton btnRegQuimico;
    private javax.swing.JButton btnRegTransporte;
    private javax.swing.JButton btnRegVehiculo;
    private javax.swing.JButton btnSaliRegistro;
    private javax.swing.JButton btnSalirProductor;
    private javax.swing.JButton btnSalirQuimico;
    private javax.swing.JButton btnSalirRegTransportista;
    private javax.swing.JButton btnSalirRegVh;
    private javax.swing.JButton btnSalirRegvAdministrador;
    private javax.swing.JComboBox<String> cmbTransportistaRegVh;
    private javax.swing.JLabel lblContraseniaRegAdministrador;
    private javax.swing.JLabel lblContraseniaRegProductor;
    private javax.swing.JLabel lblContraseniaRegTransportista;
    private javax.swing.JLabel lblNombreQuimico;
    private javax.swing.JLabel lblNombreRegAdministrador;
    private javax.swing.JLabel lblNombreRegProductor;
    private javax.swing.JLabel lblNombreRegTransportista;
    private javax.swing.JLabel lblPlacasRegVh;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblRegistrarAdministrador;
    private javax.swing.JLabel lblRegistrarProductor;
    private javax.swing.JLabel lblRegistrarTransportista;
    private javax.swing.JLabel lblRegistroVehiculos;
    private javax.swing.JLabel lblTipoVehiculoRegVh;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTransportistaRegVh;
    private javax.swing.JPanel pnlRegAdministrador;
    private javax.swing.JPanel pnlRegQuimico;
    private javax.swing.JPanel pnlRegTransporte;
    private javax.swing.JPanel pnlRegVehiculo;
    private javax.swing.JPanel pnlRegistro;
    private javax.swing.JPanel pnlRegproductor;
    private javax.swing.JTextField txtContraseniaRegAdministrador;
    private javax.swing.JTextField txtContraseniaRegProductor;
    private javax.swing.JTextField txtContraseniaRegTransportista;
    private javax.swing.JTextField txtNombreQuimico;
    private javax.swing.JTextField txtNombreRegAdministrador;
    private javax.swing.JTextField txtNombreRegProductor;
    private javax.swing.JTextField txtNombreRegTransportista;
    private javax.swing.JTextField txtPlacasRegVh;
    private javax.swing.JTextField txtTipoVehiculoRegVh;
    // End of variables declaration//GEN-END:variables

}
