/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author giova
 */
public class PrincipalForm extends javax.swing.JFrame {

    InformacionTrasladoForm informacionTrasladoForm;
    RegistroResiduoForm registroResiduoForm;
    SolicitudesTrasladosForm solicitudesTrasladosForm;
    RegistroTrasladoForm registroTrasladoForm;
    VerSolicitudesTrasladoForm verSolicitudesTrasladoForm;
    VehiculosForm vehiculosForm;
    

    public PrincipalForm() {
        initComponents();

        cargarPanel();


    }
    
    public void cargarPanel(){
        
        
        registroResiduoForm = new RegistroResiduoForm();
        pnlContent.add(registroResiduoForm, "registroResiduos");
        
        registroTrasladoForm = new RegistroTrasladoForm();
        pnlContent.add(registroTrasladoForm,"registroTraslados");
        
        solicitudesTrasladosForm = new SolicitudesTrasladosForm();
        pnlContent.add(solicitudesTrasladosForm, "solicitudTraslados");
        
        verSolicitudesTrasladoForm = new VerSolicitudesTrasladoForm();
        pnlContent.add(verSolicitudesTrasladoForm,"verSolicitudesTraslado");
        
        vehiculosForm = new VehiculosForm();
        pnlContent.add(vehiculosForm,"vehiculos");
        
    }
    
    //private 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAcceso = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnAcceso = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        btnAcercaDe = new javax.swing.JButton();
        pnlPrincipal = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnRegistrarResiduo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSolicitarRegistarTraslado = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnVerSolicitudTraslado = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnRegistrarTraslado = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnAdministracion = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de residuos peligrosos");
        setBackground(new java.awt.Color(28, 40, 51));
        getContentPane().setLayout(new java.awt.CardLayout());

        pnlAcceso.setBackground(new java.awt.Color(238, 238, 238));
        pnlAcceso.setPreferredSize(new java.awt.Dimension(1000, 620));

        lblTitulo.setBackground(new java.awt.Color(238, 238, 238));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 52)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(128, 18, 18));
        lblTitulo.setText("GESTIÓN DE RESIDUOS PELIGROSOS");

        btnAcceso.setBackground(new java.awt.Color(4, 21, 98));
        btnAcceso.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnAcceso.setForeground(new java.awt.Color(238, 238, 238));
        btnAcceso.setText("ACCESO");
        btnAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccesoActionPerformed(evt);
            }
        });

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/residuosPeligrosos.jpg"))); // NOI18N

        btnAcercaDe.setBackground(new java.awt.Color(17, 70, 143));
        btnAcercaDe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAcercaDe.setForeground(new java.awt.Color(238, 238, 238));
        btnAcercaDe.setText("Acerca de");
        btnAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaDeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAccesoLayout = new javax.swing.GroupLayout(pnlAcceso);
        pnlAcceso.setLayout(pnlAccesoLayout);
        pnlAccesoLayout.setHorizontalGroup(
            pnlAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccesoLayout.createSequentialGroup()
                .addGroup(pnlAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccesoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAcercaDe))
                    .addGroup(pnlAccesoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblTitulo)
                        .addGap(0, 53, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlAccesoLayout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(btnAcceso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccesoLayout.createSequentialGroup()
                    .addContainerGap(136, Short.MAX_VALUE)
                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(103, Short.MAX_VALUE)))
        );
        pnlAccesoLayout.setVerticalGroup(
            pnlAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccesoLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(lblTitulo)
                .addGap(152, 152, 152)
                .addComponent(btnAcceso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(btnAcercaDe)
                .addContainerGap())
            .addGroup(pnlAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccesoLayout.createSequentialGroup()
                    .addContainerGap(167, Short.MAX_VALUE)
                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(pnlAcceso, "card2");

        pnlPrincipal.setPreferredSize(new java.awt.Dimension(1000, 82));

        pnlHeader.setBackground(new java.awt.Color(4, 21, 98));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1000, 64));

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setMinimumSize(new java.awt.Dimension(236, 28));
        jPanel1.setLayout(new java.awt.CardLayout());

        btnRegistrarResiduo.setBackground(new java.awt.Color(4, 21, 98));
        btnRegistrarResiduo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnRegistrarResiduo.setForeground(new java.awt.Color(238, 238, 238));
        btnRegistrarResiduo.setText("Registrar Residuo Peligroso");
        btnRegistrarResiduo.setPreferredSize(new java.awt.Dimension(236, 28));
        btnRegistrarResiduo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarResiduoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarResiduo, "card2");

        jPanel2.setLayout(new java.awt.CardLayout());

        btnSolicitarRegistarTraslado.setBackground(new java.awt.Color(4, 21, 98));
        btnSolicitarRegistarTraslado.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSolicitarRegistarTraslado.setForeground(new java.awt.Color(238, 238, 238));
        btnSolicitarRegistarTraslado.setText("Solicitar Traslado Residuo");
        btnSolicitarRegistarTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarRegistarTrasladoActionPerformed(evt);
            }
        });
        jPanel2.add(btnSolicitarRegistarTraslado, "card2");

        jPanel3.setLayout(new java.awt.CardLayout());

        btnVerSolicitudTraslado.setBackground(new java.awt.Color(4, 21, 98));
        btnVerSolicitudTraslado.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnVerSolicitudTraslado.setForeground(new java.awt.Color(238, 238, 238));
        btnVerSolicitudTraslado.setText("Asignar Traslado a Empresa");
        btnVerSolicitudTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSolicitudTrasladoActionPerformed(evt);
            }
        });
        jPanel3.add(btnVerSolicitudTraslado, "card2");

        jPanel4.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel4.setLayout(new java.awt.CardLayout());

        btnRegistrarTraslado.setBackground(new java.awt.Color(4, 21, 98));
        btnRegistrarTraslado.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnRegistrarTraslado.setForeground(new java.awt.Color(238, 238, 238));
        btnRegistrarTraslado.setText("Registrar Traslado");
        btnRegistrarTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarTrasladoActionPerformed(evt);
            }
        });
        jPanel4.add(btnRegistrarTraslado, "card2");

        jPanel5.setLayout(new java.awt.CardLayout());

        btnAdministracion.setBackground(new java.awt.Color(4, 21, 98));
        btnAdministracion.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAdministracion.setForeground(new java.awt.Color(238, 238, 238));
        btnAdministracion.setText("Administración");
        btnAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministracionActionPerformed(evt);
            }
        });
        jPanel5.add(btnAdministracion, "card2");

        jPanel6.setLayout(new java.awt.CardLayout());

        jButton1.setBackground(new java.awt.Color(4, 21, 98));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(238, 238, 238));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, "card2");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlContent.setBackground(new java.awt.Color(238, 238, 238));
        pnlContent.setForeground(new java.awt.Color(238, 238, 238));
        pnlContent.setPreferredSize(new java.awt.Dimension(1000, 500));
        pnlContent.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                    .addComponent(pnlContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnlPrincipal, "principal");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaDeActionPerformed
        JOptionPane.showMessageDialog(this, "Gestión De Residuos Peligrosos \n Creador por:\n - Giovanni Martín Garrido Barrón\n - 228724", "Acerca De", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAcercaDeActionPerformed

    private void btnAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccesoActionPerformed

        CardLayout c1 = (CardLayout) (this.getContentPane().getLayout());
        c1.show(this.getContentPane(), "principal");
        this.setTitle("Gestión de Residuos Peligrosos");
    }//GEN-LAST:event_btnAccesoActionPerformed

    private void btnRegistrarResiduoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarResiduoActionPerformed

        CardLayout cl = (CardLayout) (pnlContent.getLayout());
        if (!registroResiduoForm.estaActivado()) {
            registroResiduoForm.cargarContenido();
        } else {
            registroResiduoForm.recargarRegistroResiduo();
        }

        cl.show(pnlContent, "registroResiduos");
        this.setTitle("Registro de Residuos");


    }//GEN-LAST:event_btnRegistrarResiduoActionPerformed

    private void btnAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministracionActionPerformed

        pnlContent.removeAll();
        cargarPanel();
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministracionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministracionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministracionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministracionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministracionForm().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnAdministracionActionPerformed

    private void btnRegistrarTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarTrasladoActionPerformed
        CardLayout cl = (CardLayout) (pnlContent.getLayout());
        if (!registroTrasladoForm.estaActivado()) {
            registroTrasladoForm.cargarContenido();
        } else {
            //actualizar datos
        }

        cl.show(pnlContent, "registroTraslados");
        this.setTitle("Registro de Traslado");
    }//GEN-LAST:event_btnRegistrarTrasladoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSolicitarRegistarTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarRegistarTrasladoActionPerformed

        CardLayout cl = (CardLayout) (pnlContent.getLayout());
        if (!solicitudesTrasladosForm.estaActivado()) {
            solicitudesTrasladosForm.cargarContenido();
        } else {
            //actualiza datos
        }

        cl.show(pnlContent, "solicitudTraslados");
        this.setTitle("Solicitar Traslado de Residuos");
    }//GEN-LAST:event_btnSolicitarRegistarTrasladoActionPerformed

    private void btnVerSolicitudTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSolicitudTrasladoActionPerformed

        CardLayout cl = (CardLayout) (pnlContent.getLayout());
        if (!verSolicitudesTrasladoForm.estaActivado()) {
            verSolicitudesTrasladoForm.cargarContenido();
        } else {
            //actualiza datos
        }

        cl.show(pnlContent, "verSolicitudesTraslado");
        this.setTitle("Ver Solicitudes de Traslado");

    }//GEN-LAST:event_btnVerSolicitudTrasladoActionPerformed

    /*

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
     */

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceso;
    private javax.swing.JButton btnAcercaDe;
    private javax.swing.JButton btnAdministracion;
    private javax.swing.JButton btnRegistrarResiduo;
    private javax.swing.JButton btnRegistrarTraslado;
    private javax.swing.JButton btnSolicitarRegistarTraslado;
    private javax.swing.JButton btnVerSolicitudTraslado;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlAcceso;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
