/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frames;

/**
 *
 * @author giova
 */
public class VehiculosForm extends javax.swing.JPanel {

    /**
     * Creates new form VehiculosForm
     */
    public VehiculosForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVehiculos = new javax.swing.JLabel();
        pnlTablaVehiculosDisponibles = new javax.swing.JScrollPane();
        tblVehiculosDisponibles = new javax.swing.JTable();
        pnlTablaVehiculosUsados = new javax.swing.JScrollPane();
        tblVehiculosUsados = new javax.swing.JTable();
        btnAgregarVehiculo = new javax.swing.JButton();
        btnEliminarVehiculo = new javax.swing.JButton();
        btnGuardarVehiculo = new javax.swing.JButton();

        lblVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblVehiculos.setText("Vehículos");

        tblVehiculosDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehículos Disponibles"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        pnlTablaVehiculosDisponibles.setViewportView(tblVehiculosDisponibles);

        tblVehiculosUsados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehículos Usados"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        pnlTablaVehiculosUsados.setViewportView(tblVehiculosUsados);

        btnAgregarVehiculo.setText("Agregar");

        btnEliminarVehiculo.setText("Eliminar");

        btnGuardarVehiculo.setText("Guardar");
        btnGuardarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardarVehiculo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(419, 419, 419)
                            .addComponent(lblVehiculos))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(175, 175, 175)
                            .addComponent(pnlTablaVehiculosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pnlTablaVehiculosUsados, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(296, 296, 296)
                            .addComponent(btnAgregarVehiculo)
                            .addGap(273, 273, 273)
                            .addComponent(btnEliminarVehiculo))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblVehiculos)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTablaVehiculosDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(pnlTablaVehiculosUsados, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarVehiculo)
                    .addComponent(btnEliminarVehiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnGuardarVehiculo)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarVehiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarVehiculo;
    private javax.swing.JButton btnEliminarVehiculo;
    private javax.swing.JButton btnGuardarVehiculo;
    private javax.swing.JLabel lblVehiculos;
    private javax.swing.JScrollPane pnlTablaVehiculosDisponibles;
    private javax.swing.JScrollPane pnlTablaVehiculosUsados;
    private javax.swing.JTable tblVehiculosDisponibles;
    private javax.swing.JTable tblVehiculosUsados;
    // End of variables declaration//GEN-END:variables
}
